import type { MenuItem } from "./menuTypes.ts";
const item = (
  categoryId: string,
  id: string,
  name: string,
  price: number,
  shortDescription: string,
  extra: Partial<MenuItem> = {},
): MenuItem => ({
  id,
  categoryId,
  name,
  price,
  shortDescription,
  description: shortDescription,
  ...extra,
});
const sauce = [
  { id: "sauce", name: "Choose your sauce", required: true, options: [] },
];
// Authoritative printed-menu GBP prices; images are representative stock.
export const menuItems: MenuItem[] = [
  item(
    "cinnamon-rolls",
    "cinnamon-roll",
    "Made daily fresh",
    4.95,
    "Freshly prepared KIVO cinnamon rolls, made daily.",
  ),
  item(
    "waffles",
    "strawberry-choc-waffle",
    "Strawberry Choc",
    7.95,
    "Fresh strawberries + sauce of your choice",
    { optionGroups: sauce },
  ),
  item(
    "waffles",
    "oreo-delight-waffle",
    "Oreo Delight",
    7.95,
    "Crushed Oreos + sauce of your choice",
    { optionGroups: sauce },
  ),
  item(
    "waffles",
    "king-ferrero",
    "King Ferrero",
    8.95,
    "Chopped nuts, Ferrero Rocher + Nutella",
    {
      popular: true,
      imageKey: "king-ferrero",
      description:
        "A waffle finished with chopped nuts, Ferrero Rocher and Nutella. A little indulgence, the KIVO way.",
    },
  ),
  item(
    "waffles",
    "kinder-bueno-waffle",
    "Kinder Bueno",
    7.95,
    "Chopped Kinder pieces, sauce of your choice",
    { optionGroups: sauce },
  ),
  item(
    "waffles",
    "lotus-waffle",
    "Lotus Waffle",
    7.95,
    "Crushed Lotus pieces, sauce of your choice",
    { optionGroups: sauce },
  ),
  item(
    "cookie-dough",
    "choc-delight-dough",
    "Choc Delight",
    6.95,
    "Milk choc sauce + soft serve",
  ),
  item(
    "cookie-dough",
    "red-velvet-dough",
    "Red Velvet",
    6.95,
    "Sauce of your choice + soft serve",
    { optionGroups: sauce },
  ),
  item(
    "cookie-dough",
    "lotus-dough",
    "Lotus",
    6.95,
    "Lotus sauce, Lotus crumbs + soft serve",
  ),
  item(
    "crepes",
    "nutella-crepe",
    "Nutella Crepe",
    6.95,
    "A delicate crêpe with the familiar indulgence of Nutella.",
  ),
  item(
    "crepes",
    "strawberry-crepe",
    "Strawberry Crepe",
    7.95,
    "Strawberry sweetness meets a delicate crêpe.",
  ),
  item(
    "crepes",
    "lotus-crepe",
    "Lotus Crepe",
    7.95,
    "A delicate crêpe with a Lotus-inspired finish.",
  ),
  item(
    "crepes",
    "banana-crepe",
    "Banana Crepe",
    7.95,
    "A delicate crêpe paired with banana.",
  ),
  item(
    "specials",
    "chocolate-strawberries",
    "Chocolate Coated Strawberries",
    4.95,
    "Strawberries dressed in chocolate. Choose your moment.",
    {
      imageKey: "chocolate-strawberries",
      variants: [
        { id: "six", name: "6 pcs", price: 4.95 },
        { id: "ten", name: "10 pcs", price: 9.95 },
      ],
    },
  ),
  item(
    "specials",
    "strawberry-kunafa-cup",
    "Strawberry Kunafa Cup",
    7.95,
    "Strawberry and kunafa, together in a cup.",
    { popular: true, imageKey: "strawberry-kunafa-cup" },
  ),
  item(
    "specials",
    "strawberry-chocolate-cup",
    "Strawberry Chocolate Cup",
    6.99,
    "A cup of strawberry and chocolate indulgence.",
  ),
  item(
    "specials",
    "tiramisu",
    "Tiramisu",
    4.95,
    "A classic tiramisu moment, to savour slowly.",
  ),
  item(
    "croffles",
    "strawberry-croffle",
    "Strawberry Croffle",
    5.99,
    "A croffle with a strawberry finish.",
    { popular: true, imageKey: "strawberry-croffle" },
  ),
  item(
    "croffles",
    "lotus-croffle",
    "Lotus Croffle",
    5.99,
    "A croffle with a little Lotus indulgence.",
  ),
  item(
    "croffles",
    "oreo-croffle",
    "Oreo Croffle",
    5.99,
    "The croffle meets the familiar taste of Oreo.",
  ),
  item(
    "croffles",
    "pistachio-croffle",
    "Pistachio Croffle",
    5.99,
    "A croffle with a pistachio finish.",
    { imageKey: "pistachio-croffle" },
  ),
  item(
    "french-toast",
    "chocolate-strawberry-toast",
    "Chocolate Strawberry French Toast",
    9.95,
    "French toast with chocolate and strawberry.",
  ),
  item(
    "french-toast",
    "pistachio-toast",
    "Pistachio",
    9.95,
    "French toast with a pistachio finish.",
  ),
  item(
    "french-toast",
    "pistachio-kunafa-toast",
    "Pistachio Kunafa",
    9.95,
    "French toast meets pistachio and kunafa.",
    { popular: true, imageKey: "pistachio-kunafa-toast" },
  ),
  item(
    "french-toast",
    "lotus-toast",
    "Lotus",
    9.95,
    "French toast with the indulgence of Lotus.",
  ),
  item(
    "french-toast",
    "mixed-berries-toast",
    "Mixed Berries",
    9.95,
    "French toast with a medley of berries.",
  ),
  item(
    "french-toast",
    "maple-syrup-toast",
    "Maple Syrup",
    9.95,
    "French toast with a maple syrup finish.",
  ),
  item(
    "smoothies",
    "strawberry-fantasy",
    "Strawberry Fantasy",
    5.99,
    "A strawberry smoothie for a bright café moment.",
    { imageKey: "strawberry-fantasy" },
  ),
  item(
    "smoothies",
    "pineapple-sunset",
    "Pineapple Sunset",
    5.99,
    "A pineapple smoothie to brighten your day.",
  ),
  item(
    "smoothies",
    "raspberry-heaven",
    "Raspberry Heaven",
    5.99,
    "A raspberry smoothie, made for a moment of pause.",
  ),
  item(
    "smoothies",
    "dazzling-dragon",
    "Dazzling Dragon",
    5.99,
    "Discover Dazzling Dragon, from our smoothie selection.",
  ),
  item(
    "cakes",
    "matilda-cake",
    "Matilda Cake",
    4.95,
    "A slice of Matilda Cake for your sweet café moment.",
    { popular: true, imageKey: "matilda-cake" },
  ),
  item(
    "cakes",
    "chocolate-fresh-cream",
    "Chocolate Fresh Cream",
    4.95,
    "Chocolate and fresh cream in a cake to savour.",
  ),
  item(
    "cakes",
    "red-velvet-fresh-cream",
    "Red Velvet Fresh Cream",
    4.95,
    "Red velvet cake with a fresh cream finish.",
  ),
  item(
    "cakes",
    "strawberry-fresh-cream",
    "Strawberry Fresh Cream",
    4.95,
    "Strawberry cake with fresh cream.",
  ),
  item(
    "cakes",
    "black-forest-fresh-cream",
    "Black Forest Fresh Cream",
    4.95,
    "Black Forest cake with a fresh cream finish.",
  ),
  item(
    "cakes",
    "lotus-cheesecake",
    "Lotus Cheesecake",
    4.95,
    "A cheesecake with a Lotus-inspired finish.",
    { imageKey: "lotus-cheesecake" },
  ),
  item(
    "cakes",
    "fudge-cake",
    "Fudge Cake",
    4.49,
    "A little fudge cake indulgence.",
  ),
  item(
    "shakes",
    "oreo-shake",
    "Oreo Shake",
    4.99,
    "An Oreo shake for your sweet side.",
    { popular: true, imageKey: "oreo-shake" },
  ),
  item(
    "shakes",
    "ferrero-rocher-shake",
    "Ferrero Rocher Shake",
    4.99,
    "Ferrero Rocher, in a shake to savour.",
  ),
  item(
    "shakes",
    "kinder-bueno-shake",
    "Kinder Bueno Shake",
    4.99,
    "A shake inspired by Kinder Bueno.",
  ),
  item(
    "shakes",
    "kinder-bueno-white-shake",
    "Kinder Bueno White Shake",
    4.99,
    "Kinder Bueno White, in a sweet shake.",
  ),
  item(
    "shakes",
    "lotus-shake",
    "Lotus Shake",
    4.99,
    "Lotus-inspired indulgence in a shake.",
  ),
  item(
    "shakes",
    "mango-milkshake",
    "Mango Milkshake",
    4.99,
    "A mango milkshake for a bright little break.",
  ),
  item(
    "shakes",
    "snickers-shake",
    "Snickers Shake",
    4.99,
    "The familiar taste of Snickers, in a shake.",
  ),
  item(
    "shakes",
    "reeses-shake",
    "Reese’s Peanut Butter Shake",
    4.99,
    "Reese’s Peanut Butter, in a shake to savour.",
  ),
  item(
    "shakes",
    "gelato-shake",
    "Gelato Shake",
    5.99,
    "A gelato shake for a little café indulgence.",
  ),
  item("drinks", "coke", "Coke", 1.99, "The classic Coke refreshment."),
  item("drinks", "coke-zero", "Coke Zero", 1.99, "A Coke Zero refreshment."),
];
